### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by paradox9955** [GarrettBlackmon/youtube-cast-receiver#6]
Can you add controller input? I know this is made to use your phone as a remote, but sometimes i wanna use a controller to control the app.

**Comment by GarrettBlackmon** [comment]
Hi,

Apologies on the very long wait for your reply. I do appreciate the request!

Just a quick question, what device are you referring to when you say
> i wanna use a controller to control the app

Can you provide a link to, product name, or photo so I can see how it works and what your intended use case is?

Any device that connects to your pc which emulates keyboard arrow key and enter presses should work.

I've used a cheap device like this in the past called a [Rii](http://www.riitek.com/) I haven't used any of their newer products but  they appear inexpensive and handy.

**Comment by paradox9955** [comment]
> Hi,
> 
> Apologies on the very long wait for your reply. I do appreciate the request!
> 
> Just a quick question, what device are you referring to when you say
> 
> > i wanna use a controller to control the app
> 
> Can you provide a link to, product name, or photo so I can see how it works and what your intended use case is?
> 
> Any device that connects to your pc which emulates keyboard arrow key and enter presses should work.
> 
> I've used a cheap device like this in the past called a [Rii](http://www.riitek.com/) I haven't used any of their newer products but they appear inexpensive and handy.

By "Controller" i meant something like an Xbox Controller. So, i could scroll through YouTube on my PC without using a Keyboard & Mouse.

**Comment by GarrettBlackmon** [comment]
>By "Controller" i meant something like an Xbox Controller. So, i could scroll through YouTube on my PC without using a Keyboard & Mouse.

Ah I understand. I have very little experience with game pad input but off the top of my head it seems like while the application is running we could re-map the controller inputs to corresponding keyboard inputs. Of course, this isn't ideal and is a hacky solution that would behave strangely if you tried to for example, game on another monitor with YCR opened. (or maybe not, you may be able to scope the inputs to just the electron instance?)

I'm certainly going to leave this up and hope someone (perhaps you could give it a crack since you would benefit from this feature 😄 ) comes along and adds this, my workload has been a bit too much to properly support this project, at least in the sense of extending functionality and increasing complexity.
